Repository SiLab-Bonn/aidatlu, pull requests merged in 2025-06, with the labels that each got.

#36 DOCS: fixed spellings for constellation spell check
  aidatlu/constellation/README.md
Labels: documentation, tests

#33 ENH: Transmit Data via Cnstln CDTP
  aidatlu/constellation/README.md
  aidatlu/constellation/__main__.py
  aidatlu/constellation/aidatlu_satellite.py
  aidatlu/constellation/example_tlu_config.toml
  aidatlu/main/config_parser.py
Labels: enhancement

#34 ENH: custom clock config files in constellation
  aidatlu/constellation/README.md
  aidatlu/constellation/aidatlu_satellite.py
  aidatlu/hardware/clock_controller.py
  aidatlu/main/config_parser.py
Labels: bug, enhancement

#44 DOC: refactored data section in constellation readme
  aidatlu/constellation/README.md
Labels: documentation
