Repository SiLab-Bonn/aidatlu, pull requests merged in 2025-04, with the labels that each got.

#25 BUG: fixed yaml dep + wrong test data output dir
  aidatlu/test/fixtures/tlu_test_configuration.yaml
  pyproject.toml
Labels: bug

#26 CI: Python versions
  .github/workflows/documentation.yml
  .github/workflows/pre_commit.yml
  .github/workflows/tests.yml
Labels: tests

#23 ENH: Improve configuration procedure and more conf file formats
  aidatlu/aidatlu_run.py
  aidatlu/main/config_parser.py
  aidatlu/main/tlu.py
  aidatlu/test/fixtures/tlu_test_configuration.toml
  aidatlu/test/fixtures/tlu_test_configuration.yaml
  aidatlu/test/test_configuration.py
  aidatlu/test/test_tlu.py
  aidatlu/tlu_configuration.yaml
Labels: enhancement

#24 Constellation satellite
  README.md
  aidatlu/README.md
  aidatlu/__init__.py
  aidatlu/constellation/README.md
  aidatlu/constellation/__main__.py
  aidatlu/constellation/aidatlu_satellite.py
  aidatlu/constellation/example_tlu_config.toml
  aidatlu/main/config_parser.py
  aidatlu/main/tlu.py
  aidatlu/test/fixtures/tlu_test_configuration.toml
  aidatlu/test/fixtures/tlu_test_configuration.yaml
  aidatlu/test/test_tlu.py
  aidatlu/tlu_configuration.yaml
  docs/source/Configuration.rst
  docs/source/Constellation.rst
  pyproject.toml
Labels: enhancement
